### ISSUE TITLE
演示账号提示密码错误

### ISSUE THREAD

**Issue by cmideal** [analysys/EasyScheduler#234]
如题

**Comment by dailidong** [comment]
Due to the large number of experiencers and the unreasonable configuration timing of individual partners (executing the process once per second), the pressure on the stand-alone machine is too large, which greatly affects the experience. To avoid this situation, please add our WeChat: denny1011 to get the trial account. , use the account, it is also easy to find the use of the partners, help to better develop easyscheduler, thank you again for your attention!

由于体验者众多，以及个别小伙伴配置定时不太合理(每秒执行一次流程)，造成单机压力过大，十分影响体验，为避免此种情况，请添加我们微信：denny1011 ，以获得开通试用账号，分账号使用，也便于发现伙伴们的使用问题，帮助更好的发展easyscheduler，再次谢谢大家的关注！
