### ISSUE TITLE
worker-server节点获取任务性能问题

### ISSUE THREAD

**Issue by ivivi** [analysys/EasyScheduler#242]
看了源码，发现下面这个问题，不知理解是否正确
worker-server节点中，当task_queue为空时，FetchTaskThread会一直循环，去获得锁，然后从task_queue里面取task，然后释放锁，但大部分时间，可能task_queue为空，这会造成不断的创建zookeeper分布式锁
1.当worker节点比较多时，对zookeeper会不会造成过多的开销
2.不知道这种设计是否还有其它用意
3.是否可以在taskQueue.poll时加一个timeout，在timeout时间内一直block着，等待task

**Comment by dailidong** [comment]
This problem is very good, and we have a good inspiration. The role of distributed locks is to prevent many workers from getting the same task. When the task queue is empty, you can not create distributed locks. The third suggestion is also great, we will optimize this part of the relevant code, thanks again.

这个问题很好，对我们有很好的启发，分布式锁的作用是为了防止很多个worker拿到同一个任务，当task queue队列为空时，可以不创建分布式锁，另外第三点建议也很棒，我们将优化这部分相关的代码，再次感谢
