### ISSUE TITLE
[BUG]Monitoring Center - Service Management only shows one device status（[BUG]监控中心-服务管理只显示一台设备状态）

### ISSUE THREAD

**Issue by zongyaoou** [analysys/EasyScheduler#645]
![image](https://user-images.githubusercontent.com/28653771/62039540-7d2d4480-b22a-11e9-9f50-7bb2bcc2bbbb.png)

As shown in the figure above, after clustering, only the status of one device is displayed. The master and worker pages have this problem.

---
![image](https://user-images.githubusercontent.com/28653771/62039540-7d2d4480-b22a-11e9-9f50-7bb2bcc2bbbb.png)

如上图 , 集群起来后 , 只显示一台设备的状态 , master , worker页面有有这个问题 ;

**Comment by boandai** [comment]
Please open debug mode on browser to find out `What is the response from the api server?`

And then you can view api server runtime log to find out `why this result responsed by the api server`

**Comment by boandai** [comment]
This did not occur in our production environment.

**Comment by zongyaoou** [comment]
> Please open debug mode on browser to find out `What is the response from the api server?`
> 
> And then you can view api server runtime log to find out `why this result responsed by the api server`

调试模式是指F12? 我翻了文档没有说怎么进入调试模式的 ;  
另外, 我非专业开发人员 , 所以麻烦操作可以说得详细一点 , 谢谢 ;

**Comment by boandai** [comment]
like this：
![image](https://user-images.githubusercontent.com/48329107/62192082-84c62800-b3a7-11e9-9cb7-521ec4b01ff7.png)

**Comment by zhangzhipeng621** [comment]
The problem is same with me, and the request that return json seem's no problem, is the font-end page has same problem?

{"code":0,"msg":"success","data":[{"id":0,"host":"**.21**","port":13393,"zkDirectory":"/escheduler/workers/xx.21_0000000000","resInfo":"{\"cpuUsage\":0.05,\"loadAverage\":0.0,\"memoryUsage\":0.22}","createTime":"2019-07-28T03:36:56.000+0000","lastHeartbeatTime":"2019-08-01T07:27:53.000+0000"},{"id":0,"host":"**.41**","port":21615,"zkDirectory":"/escheduler/workers/xx.41_0000000001","resInfo":"{\"cpuUsage\":0.16,\"loadAverage\":0.0,\"memoryUsage\":0.24}","createTime":"2019-07-28T03:36:56.000+0000","lastHeartbeatTime":"2019-08-01T07:27:43.000+0000"},{"id":0,"host":"**.61**","port":16366,"zkDirectory":"/escheduler/workers/xx.61_0000000002","resInfo":"{\"cpuUsage\":0.02,\"loadAverage\":0.0,\"memoryUsage\":0.23}","createTime":"2019-07-28T03:36:57.000+0000","lastHeartbeatTime":"2019-08-01T07:27:44.000+0000"}]}

**Comment by dailidong** [comment]
> The problem is same with me, and the request that return json seem's no problem, is the font-end page has same problem?
> 
> {"code":0,"msg":"success","data":[{"id":0,"host":"**.21**","port":13393,"zkDirectory":"/escheduler/workers/xx.21_0000000000","resInfo":"{"cpuUsage":0.05,"loadAverage":0.0,"memoryUsage":0.22}","createTime":"2019-07-28T03:36:56.000+0000","lastHeartbeatTime":"2019-08-01T07:27:53.000+0000"},{"id":0,"host":"**.41**","port":21615,"zkDirectory":"/escheduler/workers/xx.41_0000000001","resInfo":"{"cpuUsage":0.16,"loadAverage":0.0,"memoryUsage":0.24}","createTime":"2019-07-28T03:36:56.000+0000","lastHeartbeatTime":"2019-08-01T07:27:43.000+0000"},{"id":0,"host":"**.61**","port":16366,"zkDirectory":"/escheduler/workers/xx.61_0000000002","resInfo":"{"cpuUsage":0.02,"loadAverage":0.0,"memoryUsage":0.23}","createTime":"2019-07-28T03:36:57.000+0000","lastHeartbeatTime":"2019-08-01T07:27:44.000+0000"}]}

Can you attach a picture?

**Comment by William-GuoWei** [comment]
> The problem is same with me, and the request that return json seem's no problem, is the font-end page has same problem?
> 
> {"code":0,"msg":"success","data":[{"id":0,"host":"**.21**","port":13393,"zkDirectory":"/escheduler/workers/xx.21_0000000000","resInfo":"{"cpuUsage":0.05,"loadAverage":0.0,"memoryUsage":0.22}","createTime":"2019-07-28T03:36:56.000+0000","lastHeartbeatTime":"2019-08-01T07:27:53.000+0000"},{"id":0,"host":"**.41**","port":21615,"zkDirectory":"/escheduler/workers/xx.41_0000000001","resInfo":"{"cpuUsage":0.16,"loadAverage":0.0,"memoryUsage":0.24}","createTime":"2019-07-28T03:36:56.000+0000","lastHeartbeatTime":"2019-08-01T07:27:43.000+0000"},{"id":0,"host":"**.61**","port":16366,"zkDirectory":"/escheduler/workers/xx.61_0000000002","resInfo":"{"cpuUsage":0.02,"loadAverage":0.0,"memoryUsage":0.23}","createTime":"2019-07-28T03:36:57.000+0000","lastHeartbeatTime":"2019-08-01T07:27:44.000+0000"}]}

Could you attach a picture?

**Comment by zongyaoou** [comment]
> like this：
> ![image](https://user-images.githubusercontent.com/48329107/62192082-84c62800-b3a7-11e9-9cb7-521ec4b01ff7.png)
> 
> the red block is the response from api server

OK , API的返回数据如下 : 
{"code":0,"msg":"success","data":[{"id":0,"host":"172.16.20.253","port":22369,"zkDirectory":"/escheduler/workers/172.16.20.253_0000000005","resInfo":"{\"cpuUsage\":0.01,\"loadAverage\":0.0,\"memoryUsage\":0.43}","createTime":"2019-08-01T10:25:26.000+0000","lastHeartbeatTime":"2019-08-01T10:32:43.000+0000"},{"id":0,"host":"172.16.20.252","port":556,"zkDirectory":"/escheduler/workers/172.16.20.252_0000000004","resInfo":"{\"cpuUsage\":0.01,\"loadAverage\":0.0,\"memoryUsage\":0.33}","createTime":"2019-08-01T10:25:21.000+0000","lastHeartbeatTime":"2019-08-01T10:32:42.000+0000"},{"id":0,"host":"172.16.20.251","port":28066,"zkDirectory":"/escheduler/workers/172.16.20.251_0000000003","resInfo":"{\"cpuUsage\":0.01,\"loadAverage\":0.0,\"memoryUsage\":0.3}","createTime":"2019-08-01T10:25:20.000+0000","lastHeartbeatTime":"2019-08-01T10:32:45.000+0000"}]}

然后页面加载文件如下 : 
![image](https://user-images.githubusercontent.com/28653771/62286960-6d606b00-b48b-11e9-9a23-492adc245e9a.png)

**Comment by William-GuoWei** [comment]
@millionfor ，please check this issue，thx！

**Comment by chekore** [comment]
bug fixed. 
Because the row elements of the table need to be distinguished by ID, so the same ID can only be rendered on one of them(the first one).
![image](https://user-images.githubusercontent.com/8263441/62683788-e1ea5b00-b9f1-11e9-95b2-bcd92cb4c8e2.png)
![image](https://user-images.githubusercontent.com/8263441/62684070-7228a000-b9f2-11e9-87af-9776c7fb480f.png)

Fix it, as shown below(ZookeeperMonitor.java in escheduler-api module):

![image](https://user-images.githubusercontent.com/8263441/62684170-b025c400-b9f2-11e9-9dbc-2b83bf8cb09c.png)

**Comment by dailidong** [comment]
good job，thanks for a lot!

**Comment by buildupchao** [comment]
So cool! This problem will not occur in the next version?

**Comment by dailidong** [comment]
> So cool! This problem will not occur in the next version?
yes！
